name = "alkemia-fresh2"
pages_build_output_dir = "client/dist"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "alkemiafresh2"
database_id = "cca65731-628b-4fe3-b1a1-5647347c483f"

[[kv_namespaces]]
binding = "KV"
id = "32b71980aac0433d9ce10b3619f0b7bb"

[[r2_buckets]]
binding = "R2"
bucket_name = "alkemia-fresh-files"
